---
title: "phenology_plots"
author: "Abby Robinson"
date: "2024-01-23"
output: html_document
---
#load packages 
```{r Load packages}
library(curl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(spData)
library(sf)
library(maps)
library(gginnards)
library(tibble)
library(magrittr)
library(stringr)
```
#base map of USA
```{r Template map of the US}
new_map_lines5 <- ggplot() + 
  geom_polygon(data = world, aes(x=long, y=lat, group=group), color="black", fill = "white", alpha=2, size =1) +
  coord_sf(xlim = c(-98, -65), ylim = c(24, 48), expand = FALSE) +
  scale_y_continuous(breaks = seq(30, 40, 1)) +
  xlab("Longitude") +
  ylab("Latitude") +
  theme_classic() + 
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 39.5, ymax = 40.5),
            fill = "grey20", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 38.5, ymax = 39.5),
            fill = "grey70", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 37.5, ymax = 38.5),
            fill = "grey20", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 36.5, ymax = 37.5),
            fill = "grey70", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 35.5, ymax = 36.5),
            fill = "grey20", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 34.5, ymax = 35.5),
            fill = "grey70", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 33.5, ymax = 34.5),
            fill = "grey20", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 32.5, ymax = 33.5),
            fill = "grey70", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 31.5, ymax = 32.5),
            fill = "grey20", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 30.5, ymax = 31.5),
            fill = "grey70", alpha = 0.4) +
  geom_rect(aes(xmin = -98, xmax = -74, ymin = 29.5, ymax = 30.5),
            fill = "grey20", alpha = 0.4) 

new_map_lines5

ggsave(new_map_lines5, file = "/Users/abbyrobinson/Desktop/Phenology Publication/PSD_Poster/new_map_lines5.pdf", width=5, height=4, units=c("in"), useDingbats=FALSE)
```
#load data 
```{r load phenesse estimates}
setwd("/Users/abbyrobinson/Desktop/Phenology Publication/phenology_analysis") #set working directory 
estimates <- read.csv("phenesse_estimates_df.csv") #load phenesse estimates data file from working directory 

length(estimates$species) 
estimates_noNA <- na.omit(estimates) # remove rows with no data (bins that had a sample size less than 30)
length(estimates_noNA$species) 

mimicry_zone <- subset(estimates_noNA, species %in% c("archippus", "astyanax", "battus"))
mimicry_zone <- subset(mimicry_zone, latitude <= 41)

```

#plot onset and offset estimates 
```{r plot estimates }
options(repr.plot.width =10, repr.plot.height =5)

est_plot <- ggplot(data = mimicry_zone) + 
  geom_segment(aes(x = onset_low_ci, y = latitude, xend = onset_high_ci, yend = latitude,
                   color=species), size =2) +
  geom_point(aes(x = onset_estimate, y = latitude, color=species, fill=species), 
             shape =21, size = 8, color = "black") +
  geom_segment(aes(x = offset_low_ci, y = latitude, xend = offset_high_ci, yend = latitude,
                   color=species), size =2) +
  geom_point(aes(x=offset_estimate, y = latitude, color=species, fill=species), 
             shape =21, size = 8, color = "black") +
  scale_fill_manual(guide="legend", name = "Species",
                     breaks = c('battus', 'astyanax', 'archippus'),
                     values = c("navyblue","lightblue","orange"), 
                     labels = c(expression(italic("B. philenor")), 
                                expression(italic("L. a. astyanax")), 
                                expression(italic("L. archippus")))) +
    scale_color_manual(guide="legend", name = "Species",
                     breaks = c('battus', 'astyanax', 'archippus'),
                     values = c("navyblue","lightblue","orange"), 
                     labels = c(expression(italic("B. philenor")), 
                                expression(italic("L. a. astyanax")), 
                                expression(italic("L. archippus")))) +
  labs(x = "Julian Day", y = "Latitude")  +
  scale_y_continuous(breaks = seq(16, 43, 1))  + 
  expand_limits(y = c(16, 43), x = c(0, 365)) +
  theme_classic() + 
  theme(axis.ticks = element_line(size = 2, color="black") , 
        axis.ticks.length = unit(.5, "cm"), 
        axis.title = element_text( color="black", size=20, face=2),
        axis.line = element_line(size = 3, colour = "black", linetype=1),
        axis.text = element_text(color="black", size=25, face=1)
        ) 
est_plot
```
#plot onset for latitudes 30 - 40 
```{r plot onset }
options(repr.plot.width =10, repr.plot.height =5)
mimicry_zone_30_40 <- subset(mimicry_zone, latitude %in% 30:40)

est_plot_onset <- ggplot(data = mimicry_zone_30_40) + 
  geom_segment(aes(x = onset_low_ci, y = latitude, xend = onset_high_ci, yend = latitude,
                   color=species), size =2) +
  geom_point(aes(x = onset_estimate, y = latitude, color=species, fill=species), 
             shape =21, size = 8, color = "black") +
  scale_fill_manual(guide="legend", name = "Species",
                     breaks = c('battus', 'astyanax', 'archippus'),
                     values = c("navyblue","lightblue","orange"), 
                     labels = c(expression(italic("B. philenor")), 
                                expression(italic("L. a. astyanax")), 
                                expression(italic("L. archippus")))) +
    scale_color_manual(guide="legend", name = "Species",
                     breaks = c('battus', 'astyanax', 'archippus'),
                     values = c("navyblue","lightblue","orange"), 
                     labels = c(expression(italic("B. philenor")), 
                                expression(italic("L. a. astyanax")),
                                expression(italic("L. archippus")))) +
  labs(x = "Julian Day", y = "Latitude")  +
  scale_y_continuous(breaks = seq(30, 40, 1))  + 
  expand_limits(y = c(30, 40), x = c(75, 175)) +
  theme_classic() + 
  theme(axis.ticks = element_line(size = 2, color="black") , 
        axis.ticks.length = unit(.5, "cm"), 
        axis.title = element_text( color="black", size=20, face=2),
        axis.line = element_line(size = 3, colour = "black", linetype=1),
        axis.text = element_text(color="black", size=25, face=1)
        ) 
est_plot_onset
ggsave(est_plot_onset, file = "/Users/abbyrobinson/Desktop/Phenology Publication/phenology_analysis/est_plot_onset.pdf", width=15, height=5, units=c("in"), useDingbats=FALSE)
```




